#baseURL = "https://akavel.github.io/"
baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "akavel"
#theme = "hugo-lithium-theme"
#theme = "heathen-hugo" # ~
#theme = "slim"  # cool but with bugs
#theme = "hugo-zen" # ok
#theme="hugo-theme-mijnimal" # ~
#theme="gindoro" # cool but not perfect
#theme="hemingway" # eh, too thin
#theme="hugo-theme-vec" # uh? mucho brokenish
#theme="hugo-morphism" # broken
theme="simple-a" # pretty! wraps <pre>
#theme="cocoa-hugo-theme" # broken
#theme="hugo-steam-theme" # broken
#theme="cocoa-eh" #broken
#theme="sustain" # ~
#theme="crisp" # nah.
#theme="amp" # borken!
#theme="minos"  # has potential
